spring.application.name=PaymentService
server.port=8585
stripe.key.secret=${STRIPE_SECRET_KEY:dummy-stripe-key}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${USER_SERVICE_JWK_SET_URI:http://localhost:8082/.well-known/jwks.json}
